# Exercise sheet \#2


## Exercise 1
In this exercise, we will program an ATM. An ATM is a device which can deliver/receive bank notes to/from customers, depending on the amount of money they have on their bank account.

### Question 1.1
First, we will represent customers as entities whose attributes are:
- name (str)
- birthdate (str of the form xx/xx/xxxx)
- account_number (str)
- secret_code (str) made of 4 digits
- balance (float)

Define a class `Customer` together with its `__init__` method allowing users to create customers.


In [8]:
# Question 1.1
class Customer:

    def __init__(self, name, birthdate, account_number, secret_code, balance):
        self.name = name
        self.birthdate = birthdate
        self.account_number = account_number
        self.secret_code = secret_code
        self.balance = balance
    # Question 1.2
    def debit(self, number):
        if number <= self.balance:
            self.balance -= number
            return self.balance
        else:
            print("Warning! Insufficient balance.")
            return None
    # Question 1.3
    def credit(self,ask_money):
        if ask_money < 0:
            print('Invalid input')
            return None
        else:
            self.balance +=ask_money
        return self.balance 
    # Question 1.4
    def __str__(self):

        return f"{self.name}, born on {self.birthdate}, account {self.account_number}, {self.balance:.2f} EUR"
        

In [17]:
person = Customer("Pierre Poljak", "2002/06/12","001213",74289457,2504.2526262727)
print(str(person))

Pierre Poljak, born on 2002/06/12, account 001213, 2504.25 EUR


### Question 1.2
Add a method `debit` in the class `customer` which takes as an input a float and if there is enough money on the bank account, decreases the balance accordingly. If this is not the case, this method will print a warning message on the console and return `None`.

### Question 1.3
Add a method `credit` to the class `customer` which can be used to increase the amount of money of the curstomer's account.

### Question 1.4
In some context, one may be interested in displaying the pieces of information which characterize a given customer. To do so, we use a method named `__str__` and which is invoked when we call `print(str(x))` with `x` of type `customer`.
Define this method to return strings of the following form:

`Pierre Poljak, born on 2002/06/12, account 001213, 2504.25 EUR` 

### Question 1.5
We will now define an `ATM` class, whose attributes are:
 - a list of customers `lcustomers`
 - a number of 50-EUR bank notes `n50`
 - a number of 20-EUR bank notes `n20`
 - a number of 10-EUR bank notes `n10`
 
together with an `__init__` method so that ATMs can be created.

In [19]:
class ATM:

    def __init__(self, lcustomers,n50,n20,n10):
        self.lcustomers = lcustomers
        self.n50 = n50
        self.n20 = n20
        self.n10 = n10
    # Question 1.6
    def verify(self, account_number,secret_code):
        for customer in self.lcustomers:
            if customer.account_number == account_number and customer.secret_code == secret_code:
                return True
           
        return False
    # Question 1.7
    def change(self, amount):
        if amount % 10 != 0:
            print('available withdraws are multiple of 10 EUR')
            return None
        else:
            n50 = amount // 50
            n20 = (amount % 50) // 20
            n10 = (amount % 20) // 10
            return (n10, n20, n50)      
    def debit(self, user, amount):
        n10, n20, n50 = self.change(amount)
        if n50 <= self.n50 and n20 <= self.n20 and n10 <= self.n10:
            self.n50 = self.n50 - n50
            self.n20 = self.n20 - n20
            self.n10 = self.n10 - n10
            user.debit(amount)
        else:
            print('Not enough bank notes remaining')
            
    def credit(self, user, amount):
        user.credit(amount)        
        
    def run(self):
        quit = False
        while not quit:
            an = input('Please enter your account number:')
            sc = input('Please enter your secret code:')
            c  = self.verify(an, sc)
            if c is not None:
                op = input('Operation (1-> debit / 2-> credit / 3-> print info / 4-> quit):')
                if op == '1':
                    amount = input('amount:')
                    self.debit(c, float(amount))
                elif op == '2':
                    amount = input('amount:')
                    self.credit(c, float(amount))
                elif op == '3':
                    print(c)
                else:
                    quit = True

        
        

In [20]:
if __name__=='__main__':
    print('Welcome')
    customer1 = Customer('Pierre Poljak', '2002/06/12', '001213', '0000', 2504.25)
    customer2 = Customer('Matthieu Poljak', '2006/03/18', '001214', '0110', 504.45)
    customer3 = Customer('Louis Poljak', '1998/12/12', '001215', '0020', 20004.23)
    customer4 = Customer('Sophie Poljak', '2000/02/02', '001216', '0200', 5502.00)
    atm = ATM([customer1, customer2, customer3, customer4], 20, 20, 20)
    atm.run()

Welcome


Please enter your account number: 001213
Please enter your secret code: 0000
Operation (1-> debit / 2-> credit / 3-> print info / 4-> quit): 3


True


Please enter your account number: 001213
Please enter your secret code: 0000
Operation (1-> debit / 2-> credit / 3-> print info / 4-> quit): 3


True


Please enter your account number: 4
Please enter your secret code: 4
Operation (1-> debit / 2-> credit / 3-> print info / 4-> quit): 4


### Question 1.6
Add to the ATM class, a method `verify` which takes as an input an account number, and a secret code, and check (i) whether the account number is valid (that is, whether it appears among the customers), and (ii) whether the given secret code is identical to the secret code stored in the corresponding customer's pieces of information. This method returns `True` if the verification succeeds and `False` otherwise.

### Question 1.7
Define a method `change` which computes, for a given amount of money, the corresponding numbers of 10, 20 and 50 bank-notes.

### Question 1.8
Add to the ATM class, two methods named `debit` and `credit` which takes as inputs an account number and an amount of money, and applies the corresponding debit/credit (do not forget to check that there are enough bank notes in the ATM). These methods returns the new customer balance. 

### Question 1.9
Add to the ATM class a method `run` which execute an infinite loop, waiting for a user to enter an account number. When such a number is typed, it then asks for the secret code, and if it succeeds, it displays a menu allowing the user to either withdraw money or make a deposit. 

### Question 1.10
Finally, run the following code (it should not trigger any error):

## Exercise 2
In this exercise, we will use the `list` class provided by Python.
First, let us check that lists are indeed classes:

In [21]:
l = [2,4,5]
type(l)

list

The `help` function permits us to list the methods available for using lists

In [22]:
help(l)

Help on list object:

class list(object)
 |  list(iterable=(), /)
 |  
 |  Built-in mutable sequence.
 |  
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate sign

The list class will be used to implement a basic _calculator_, which can only compute the value of arithmetic expressions written in the [Reverse Polish Notation](https://en.wikipedia.org/wiki/Reverse_Polish_notation).
For instance, it can compute the results of expressions such as "3 2 + 5 *" (which gives 25).

To do this, it uses a stack. More precisely, it reads the expression from left to right, when a number is read, it goes onto the stack, when an operator is read, the two numbers of the top of the stack are retrieved, the elementary computation is done and the result is stored back onto the stack. When the expression has been processed, the result of the evaluation can be found on the top of the stack, as illustrated below:

![rpn](images/NPI_stack.jpg)

### Question 2.1
Define a `stack` class which contains an attribute of type `list` named `l`, and the following methods:

- `_init__` (which creates an empty stack)
- `push` (which push some value onto the stack)
- `pop` (which returns the value on the top of the stack and removes it from the stack)


In [38]:
class stack:
    def __init__(self):
        self.l = []
    def push(self,v):
        self.l.append(v)
    def pop(self):
        self.l.pop()

### Question 2.2
Define a class `calculator` which contains an attribute `memory` of type `stack` together with the following methods:

- `__init__` (which launches a calculator)
- `eval` (which takes an arithmetic expression such as "3 5 +" as input and returns its value ; note that numbers and operators are separated by singles spaces)


In [39]:
class calculator:

    def __init__(self):

        self.memory = stack()
    
    def eval(exp):
        
        tokens = exp.split(' ')
        for t in tokens:
            if t in ['-','+', '*', '/']:
                val2 = self.memory.pop()
                val1 = self.memory.pop()
                if t == '+':
                    self.memory.push(val1 + val2)
                elif t == '-':
                    self.memory.push(val1 - val2)
                elif t == '*':
                    self.memory.push(val1 * val2)
                elif t == '/':
                    self.memory.push(val1 / val2)
            elif t.isdigit():
                self.memory.push(int(t))
        return self.memory.pop()

### Question 3.3
Uncomment and run the code below:

In [40]:
if __name__=='__main__':
    c = calculator()
    e = input('Please enter an expression in Reverse Polish Notation:')
    print(c.eval(e))
    pass

Please enter an expression in Reverse Polish Notation: 3 5 + 4 -


TypeError: calculator.eval() takes 1 positional argument but 2 were given